Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 551, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Instantiate learner in VW
vw = pyvw.Workspace("--cb_explore_adf -q UA --quiet --epsilon 0.2")

num_iterations = 5000
ctr = run_simulation(vw, num_iterations, users, times_of_day, actions, get_cost)

plot_ctr(num_iterations, ctr)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [11][0m, in [0;36m<module>[0;34m[0m
[1;32m      2[0m vw [38;5;241m=[39m pyvw[38;5;241m.[39mWorkspace([38;5;124m"[39m[38;5;124m--cb_explore_adf -q UA --quiet --epsilon 0.2[39m[38;5;124m"[39m)
[1;32m      4[0m num_iterations [38;5;241m=[39m [38;5;241m5000[39m
[0;32m----> 5[0m ctr [38;5;241m=[39m [43mrun_simulation[49m[43m([49m[43mvw[49m[43m,[49m[43m [49m[43mnum_iterations[49m[43m,[49m[43m [49m[43musers[49m[43m,[49m[43m [49m[43mtimes_of_day[49m[43m,[49m[43m [49m[43mactions[49m[43m,[49m[43m [49m[43mget_cost[49m[43m)[49m
[1;32m      7[0m plot_ctr(num_iterations, ctr)

Input [0;32mIn [9][0m, in [0;36mrun_simulation[0;34m(vw, num_iterations, users, times_of_day, actions, cost_function, do_learn)[0m
[1;32m     17[0m cost_sum [38;5;241m+[39m[38;5;241m=[39m cost
[1;32m     19[0m [38;5;28;01mif[39;00m do_learn:
[1;32m     20[0m     [38;5;66;03m# 5. Inform VW of what happened so we can learn from it[39;00m
[0;32m---> 21[0m     vw_format [38;5;241m=[39m vw[38;5;241m.[39mparse(to_vw_example_format(context, actions, (action, cost, prob)),[43mpyvw[49m[38;5;241;43m.[39;49m[43mvw[49m[38;5;241;43m.[39;49m[43mlContextualBandit[49m)
[1;32m     22[0m     [38;5;66;03m# 6. Learn[39;00m
[1;32m     23[0m     vw[38;5;241m.[39mlearn(vw_format)

[0;31mAttributeError[0m: type object 'vw' has no attribute 'lContextualBandit'
AttributeError: type object 'vw' has no attribute 'lContextualBandit'

