Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
iris_dataset = sklearn.datasets.load_iris()
iris_dataframe = pd.DataFrame(
    data=iris_dataset.data, columns=iris_dataset.feature_names)
# vw expects labels starting from 1
iris_dataframe["y"] = iris_dataset.target + 1
training_data, testing_data = sklearn.model_selection.train_test_split(
    iris_dataframe, test_size=0.2)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m/tmp/ipykernel_286/1031728472.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0miris_dataset[0m [0;34m=[0m [0msklearn[0m[0;34m.[0m[0mdatasets[0m[0;34m.[0m[0mload_iris[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m iris_dataframe = pd.DataFrame(
[1;32m      3[0m     data=iris_dataset.data, columns=iris_dataset.feature_names)
[1;32m      4[0m [0;31m# vw expects labels starting from 1[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0miris_dataframe[0m[0;34m[[0m[0;34m"y"[0m[0;34m][0m [0;34m=[0m [0miris_dataset[0m[0;34m.[0m[0mtarget[0m [0;34m+[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'sklearn' has no attribute 'datasets'
AttributeError: module 'sklearn' has no attribute 'datasets'

